
    <x-filament::page>
        <div class="text-center space-y-6">
            <h2 class="text-3xl font-bold text-primary-700">Bienvenido al Sistema de Información de Eventos Académicos</h2>
            <p class="text-gray-900 dark:text-gray-100">La prestigiosa Facultad Nacional de Ingeniería, fue creada un 3 de julio de 1906 como Escuela de Minas a fin de cubrir la demanda de los recursos humanos capacitados para desempeñarse en la industria minera del País, que en ese entonces se constituía en el pilar más importante de la economía del Estado Boliviano. Durante la Guerra del Chaco, iniciada en 1932, la Escuela de Minas interrumpió sus labores académicas a partir de la gestión 1933 y en el lapso de 1933-1935, sus ambientes fueron empleados como hospital militar. Después de finalizada la guerra el año 1935, en merito a los servicios prestados al país, la Escuela de Minas es elevada al rango de "Facultad de Minas y Petróleos", con el aditamento de la especialidad de petróleo. Sensiblemente esta nueva unidad académica con las especialidades de Minas y Petróleo, funciona solamente hasta el año 1938. En este año, mediante Resolución de Consejo Universitario se aprueba el nuevo pensum y el cambio a "Facultad Nacional de Ingeniería de Minas y Petróleos", sin embargo, la falta de presupuesto ocasiono serios conflictos y por la carencia de docentes para las asignaturas de petróleo, se decretó la desaparición de este pensum a corto plazo. A fines de 1940, se solicita un nuevo local para la instalación de maquinaria y mejoras en los laboratorios y gabinetes de la Facultad, iniciativa que queda postergada hasta después de tres décadas. Con la creación de la sección Ingeniería Civil, en marzo de 1941 mediante Resolución del Consejo Universitario la Facultad cambia a "Facultad Nacional de Ingeniería - F.N.I.", en el entendido que esta nueva nominación involucraría en si todas las ramas de ingeniería a crearse en el futuro conforme a las necesidades del País..</p>
            <img src="{{ asset('images/f.png') }}" alt="Banner de eventos" class="mx-auto w-1/2 rounded-lg shadow-lg">
        </div>
    </x-filament::page>

